# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Density Estimation Trees (DET)
#'
#' @param data matrix (rows are observations; columns are variables)
#' @param folds number of folds for k-fold cross validation (0 does LOO-CV)
#' @param volreg
#' @param maxsize
#' @param minsize
#'
#' @export
ml_det <- function(dataset, folds = 10L, volreg = FALSE, maxsize = 10L, minsize = 5L) {
    .Call('_det11_ml_det', PACKAGE = 'det11', dataset, folds, volreg, maxsize, minsize)
}

