// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppMLPACK.h>
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// mlkmeans
List mlkmeans(const arma::mat& data, const int& clusters);
RcppExport SEXP _det11_mlkmeans(SEXP dataSEXP, SEXP clustersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const int& >::type clusters(clustersSEXP);
    rcpp_result_gen = Rcpp::wrap(mlkmeans(data, clusters));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_det11_mlkmeans", (DL_FUNC) &_det11_mlkmeans, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_det11(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
