// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// TSDE
void TSDE(const Rcpp::NumericMatrix& data, const size_t nmbcuts, const double lower00, const double upper00, const double csmooth, const size_t sizetre);
RcppExport SEXP _tsde94_TSDE(SEXP dataSEXP, SEXP nmbcutsSEXP, SEXP lower00SEXP, SEXP upper00SEXP, SEXP csmoothSEXP, SEXP sizetreSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const size_t >::type nmbcuts(nmbcutsSEXP);
    Rcpp::traits::input_parameter< const double >::type lower00(lower00SEXP);
    Rcpp::traits::input_parameter< const double >::type upper00(upper00SEXP);
    Rcpp::traits::input_parameter< const double >::type csmooth(csmoothSEXP);
    Rcpp::traits::input_parameter< const size_t >::type sizetre(sizetreSEXP);
    TSDE(data, nmbcuts, lower00, upper00, csmooth, sizetre);
    return R_NilValue;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _tsde94_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tsde94_TSDE", (DL_FUNC) &_tsde94_TSDE, 6},
    {"_tsde94_rcpp_hello_world", (DL_FUNC) &_tsde94_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_tsde94(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
