# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' TSDE algorithm
#'
#'
#'
#'
#' @param data the input data (unstandardized)
#' @param nmbcuts number of possible splitting points
#' @param lower00 lower bound of data (in units of standard deviations)
#' @param upper00 upper bound of data (in units of standard deviations)
#'
#' @export
TSDE <- function(data, nmbcuts = 100L, lower00 = -3.5, upper00 = 3.5) {
    invisible(.Call('_tsde94_TSDE', PACKAGE = 'tsde94', data, nmbcuts, lower00, upper00))
}

rcpp_hello_world <- function() {
    .Call('_tsde94_rcpp_hello_world', PACKAGE = 'tsde94')
}

