# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
TSDE <- function(data) {
    invisible(.Call('_tsde94_TSDE', PACKAGE = 'tsde94', data))
}

rcpp_hello_world <- function() {
    .Call('_tsde94_rcpp_hello_world', PACKAGE = 'tsde94')
}

